# Introducción a Numpy

Numpy es la principal biblioteca con herramientas propias de computación científica en Python. Numpy permite manipular rapidamente arreglos, contiene funciones de álgebre lineal, funciones como $exp(x), log(x)$, trigonométricas entre otras. Estas funciones reciben arreglos y devuelven arreglos.

Su unidad básica es el tipo $ \huge \textbf{numpy.array}$

Contenido:

* Arreglos 1D
* Arreglos 2D
* Acceso a los elementos de un arreglo
* Mascara: acceso a lementos por condiciones
* Operaciones aritmeticas entre arreglos Numpy
* Funciones de Numpy
* Utilidades de algebra lineal en Numpy
* Otras funcionalidades de Numpy

In [1]:
import numpy as np

# 1D Numpy Array

In [8]:
a_1D_list = [1, 2, 3]

In [12]:
a_numpy_array = np.array(a_1D_list)

In [18]:
print("a_numpy_array = ", a_numpy_array)
print(type(a_numpy_array))
print("Lenght: ", len(a_numpy_array))
print("Dimensiones: ", a_numpy_array.shape)

a_numpy_array =  [1 2 3]
<class 'numpy.ndarray'>
Lenght:  3
Dimensiones:  (3,)


# 2D array

In [24]:
a_2D_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
a_numpy_array = np.array(a_2D_list)

In [25]:
print("a_numpy_array = \n", a_numpy_array)
print(type(a_numpy_array))
print("Lenght: ", len(a_numpy_array))
print("Dimensiones y 'Shape': ", a_numpy_array.shape)

a_numpy_array = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>
Lenght:  4
Dimensiones y 'Shape':  (4, 3)


# Acceso a los elementos de un arreglo

$ \textbf{Un elemento} \hspace{1.5cm} \huge array[<rowIndex>][<columnIndex>] $

$ \textbf{Multiples elementos (usar : )} \hspace{1.5cm} \huge array[:] $

### Filas

In [46]:
print("a_numpy_array = \n", a_numpy_array)
print("\nNúmero de filas: ", len(a_numpy_array[:]))
print("Fila 1:", a_numpy_array[0])
print("Fila 2:", a_numpy_array[1])
print("Fila 3:", a_numpy_array[2])
print("Fila 4:", a_numpy_array[3])

a_numpy_array = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Número de filas:  4
Fila 1: [1 2 3]
Fila 2: [4 5 6]
Fila 3: [7 8 9]
Fila 4: [10 11 12]


In [52]:
for row in a_numpy_array:
    print("row:", row)

row: [1 2 3]
row: [4 5 6]
row: [7 8 9]
row: [10 11 12]


### Columnas

In [47]:
print("a_numpy_array = \n", a_numpy_array)
print("\nNúmero de columnas: ", len(a_numpy_array[0,:]))
print("Columna 1:", a_numpy_array[:,0])
print("Columna 2:", a_numpy_array[:,1])
print("Columna 3:", a_numpy_array[:,2])

a_numpy_array = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Número de columnas:  3
Columna 1: [ 1  4  7 10]
Columna 2: [ 2  5  8 11]
Columna 3: [ 3  6  9 12]


In [55]:
for column in a_numpy_array.T:
    print("column:", column)

column: [ 1  4  7 10]
column: [ 2  5  8 11]
column: [ 3  6  9 12]


## Accediendo a los elementos de arreglos por índices enteros

In [62]:
a_numpy_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### Elemento de la fila 3 (indice 2), columna 2 (indice 1)

In [70]:
a_numpy_array[2][1]

8

#### Indices negativos: para acceder a los elementos del arreglo desde el final
Último elemento (ultima columna, ultima fila)

In [66]:
a_numpy_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
a_numpy_array[-1][-1]

12

## Accediendo a los elementos de arreglos por arreglos de índices

In [57]:
a_numpy_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### Seleccionar las filas 3 y 4

In [61]:
a_numpy_array[[2, 3]]

array([[ 7,  8,  9],
       [10, 11, 12]])

#### Seleccionar las columnas 1 y 3

In [78]:
a_numpy_array[:,[0, 2]]

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

## Acceder a elementos de un arreglo por arreglo de condiciones: Máscara

#### Seleccionar los elementos pares

In [79]:
a_numpy_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [74]:
even_numbers_condition = a_numpy_array%2 == 0
print(even_numbers_condition)

[[False  True False]
 [ True False  True]
 [False  True False]
 [ True False  True]]


In [80]:
a_numpy_array[even_numbers_condition]

array([ 2,  4,  6,  8, 10, 12])

### Condiciones compuestas

#### Seleccionar los numeros pares menores e iguales a 6:

In [89]:
even_less_6_condition = (a_numpy_array%2 == 0) & (a_numpy_array <= 6)
print(even_less_6_condition)

[[False  True False]
 [ True False  True]
 [False False False]
 [False False False]]


In [90]:
a_numpy_array[even_less_6_condition]

array([2, 4, 6])

#### Seleccionar los elementos pares usando np.where()

In [85]:
where_even_numbers = np.where( a_numpy_array%2 == 0 )

In [88]:
print(where_even_numbers)

(array([0, 1, 1, 2, 3, 3]), array([1, 0, 2, 1, 0, 2]))


In [87]:
a_numpy_array[where_even_numbers]

array([ 2,  4,  6,  8, 10, 12])

# Operaciones aritméticas entre arreglos Numpy

In [93]:
a = np.array([1, 2, 3, 4])
b = np.array([0, 2, 4, 6])

In [99]:
print("a+b =", a+b)
print("a-b =", a-b)
print("a*b =", a*b)
print("a/b =", a/b)
print("a**b =", a**b)
print("a//b =", a//b)

a+b = [ 1  4  7 10]
a-b = [ 1  0 -1 -2]
a*b = [ 0  4 12 24]
a/b = [       inf 1.         0.75       0.66666667]
a**b = [   1    4   81 4096]
a//b = [0 1 0 0]


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in floor_divide
  


# Comparación entre arreglos Numpy

In [100]:
a = np.array([1, 2, 3, 4])
b = np.array([0, 2, 4, 6])

In [103]:
print("a == b =", a==b)
print("a != b =", a!=b)
print("a > b =", a>b)


a == b = [False  True False False]
a != b = [ True False  True  True]
a > b = [ True False False False]


# Operaciones de lógica entre arreglos Numpy

In [113]:
a = np.array([True, True, False, True])
b = np.array([False, True, False, True])

In [115]:
print("a and b =", (a.any() and b))
print("")
print("a or b =", (a.any() or b))
print("not b =", not b.all())


a and b = [False  True False  True]

a or b = True
not b = True


# Otras utilidades de Numpy

In [69]:
help(np.where)

Help on built-in function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called whe

In [77]:
help(np.dot)

Help on built-in function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
 

In [119]:
help(np.zeros)

help(np.ones)


Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [49]:
c = np.full((2,2), 7)  # Create a constant array
print(c)  

[[7 7]
 [7 7]]


In [118]:
help(np.eye)
help(np.random.random)


Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -