# Introducción a Numpy

Numpy es la principal biblioteca con herramientas propias de computación científica en Python. Numpy permite manipular rapidamente arreglos, contiene funciones de álgebre lineal, funciones como $exp(x), log(x)$, trigonométricas entre otras. Estas funciones reciben arreglos y devuelven arreglos.

Su unidad básica es el tipo $ \huge \textbf{numpy.array}$

Contenido:

* Arreglos 1D
* Arreglos 2D
* Acceso a los elementos de un arreglo
* Mascara: acceso a lementos por condiciones
* Operaciones aritmeticas entre arreglos Numpy
* Constantes
* Funciones de Numpy
* Utilidades de algebra lineal en Numpy
* Otras funcionalidades de Numpy

In [3]:
import numpy as np

# 1D Numpy Array

In [8]:
a_1D_list = [1, 2, 3]

In [12]:
a_numpy_array = np.array(a_1D_list)

In [18]:
print("a_numpy_array = ", a_numpy_array)
print(type(a_numpy_array))
print("Lenght: ", len(a_numpy_array))
print("Dimensiones: ", a_numpy_array.shape)

a_numpy_array =  [1 2 3]
<class 'numpy.ndarray'>
Lenght:  3
Dimensiones:  (3,)


# 2D array

In [4]:
a_2D_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
a_numpy_array = np.array(a_2D_list)

In [25]:
print("a_numpy_array = \n", a_numpy_array)
print(type(a_numpy_array))
print("Lenght: ", len(a_numpy_array))
print("Dimensiones y 'Shape': ", a_numpy_array.shape)

a_numpy_array = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>
Lenght:  4
Dimensiones y 'Shape':  (4, 3)


# Acceso a los elementos de un arreglo

$ \textbf{Un elemento} \hspace{1.5cm} \huge array[<rowIndex>][<columnIndex>] $

$ \textbf{Multiples elementos (usar : )} \hspace{1.5cm} \huge array[:] $

### Filas

In [46]:
print("a_numpy_array = \n", a_numpy_array)
print("\nNúmero de filas: ", len(a_numpy_array[:]))
print("Fila 1:", a_numpy_array[0])
print("Fila 2:", a_numpy_array[1])
print("Fila 3:", a_numpy_array[2])
print("Fila 4:", a_numpy_array[3])

a_numpy_array = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Número de filas:  4
Fila 1: [1 2 3]
Fila 2: [4 5 6]
Fila 3: [7 8 9]
Fila 4: [10 11 12]


In [52]:
for row in a_numpy_array:
    print("row:", row)

row: [1 2 3]
row: [4 5 6]
row: [7 8 9]
row: [10 11 12]


### Columnas

In [47]:
print("a_numpy_array = \n", a_numpy_array)
print("\nNúmero de columnas: ", 
      len(a_numpy_array[0,:]))
print("Columna 1:", a_numpy_array[:,0])
print("Columna 2:", a_numpy_array[:,1])
print("Columna 3:", a_numpy_array[:,2])

a_numpy_array = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Número de columnas:  3
Columna 1: [ 1  4  7 10]
Columna 2: [ 2  5  8 11]
Columna 3: [ 3  6  9 12]


In [55]:
for column in a_numpy_array.T:
    print("column:", column)

column: [ 1  4  7 10]
column: [ 2  5  8 11]
column: [ 3  6  9 12]


## Accediendo a los elementos de arreglos por índices enteros

In [62]:
a_numpy_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### Elemento de la fila 3 (indice 2), columna 2 (indice 1)

In [70]:
a_numpy_array[2][1]

8

#### Indices negativos: para acceder a los elementos del arreglo desde el final
Último elemento (ultima columna, ultima fila)

In [66]:
a_numpy_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
a_numpy_array[-1][-1]

12

## Accediendo a los elementos de arreglos por arreglos de índices

In [57]:
a_numpy_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### Seleccionar las filas 3 y 4

In [61]:
a_numpy_array[[2, 3]]

array([[ 7,  8,  9],
       [10, 11, 12]])

#### Seleccionar las columnas 1 y 3

In [78]:
a_numpy_array[:,[0, 2]]

array([[ 1,  3],
       [ 4,  6],
       [ 7,  9],
       [10, 12]])

## Acceder a elementos de un arreglo por arreglo de condiciones: Máscara

#### Seleccionar los elementos pares

In [79]:
a_numpy_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [74]:
even_numbers_condition = a_numpy_array%2 == 0
print(even_numbers_condition)

[[False  True False]
 [ True False  True]
 [False  True False]
 [ True False  True]]


In [80]:
a_numpy_array[even_numbers_condition]

array([ 2,  4,  6,  8, 10, 12])

### Condiciones compuestas

#### Seleccionar los numeros pares menores e iguales a 6:

In [7]:
even_less_6_condition = (a_numpy_array%2 == 0) & (a_numpy_array <= 6)
print(even_less_6_condition)

[[False  True False]
 [ True False  True]
 [False False False]
 [False False False]]


In [8]:
a_numpy_array[even_less_6_condition]

array([2, 4, 6])

#### Seleccionar los elementos pares usando np.where()

In [10]:
where_even_numbers = np.where( a_numpy_array%2 == 0 )

In [11]:
print(where_even_numbers)

(array([0, 1, 1, 2, 3, 3]), array([1, 0, 2, 1, 0, 2]))


In [87]:
a_numpy_array[where_even_numbers]

array([ 2,  4,  6,  8, 10, 12])

# Operaciones aritméticas entre arreglos Numpy

In [93]:
a = np.array([1, 2, 3, 4])
b = np.array([0, 2, 4, 6])

In [99]:
print("a+b =", a+b)
print("a-b =", a-b)
print("a*b =", a*b)
print("a/b =", a/b)
print("a**b =", a**b)
print("a//b =", a//b)

a+b = [ 1  4  7 10]
a-b = [ 1  0 -1 -2]
a*b = [ 0  4 12 24]
a/b = [       inf 1.         0.75       0.66666667]
a**b = [   1    4   81 4096]
a//b = [0 1 0 0]


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in floor_divide
  


# Comparación entre arreglos Numpy

In [100]:
a = np.array([1, 2, 3, 4])
b = np.array([0, 2, 4, 6])

In [103]:
print("a == b =", a==b)
print("a != b =", a!=b)
print("a > b =", a>b)


a == b = [False  True False False]
a != b = [ True False  True  True]
a > b = [ True False False False]


# Operaciones lógicas entre arreglos Numpy

In [8]:
a = np.array([True, True, False, True])

In [11]:
print("True and a =", True and b)
print("False or a =", False or b)


True and a = [False  True False  True]
False or a = [False  True False  True]
not a = False


### Uso de any() y all()

$ \textbf{any()} $ Evalúa si cualquiera de los elementos de un arreglo es True

$ \textbf{all()} $ Evalúa si todos los elementos de un arreglo es True

In [12]:
a = np.array([True, True, False, True])

In [13]:
a.all()

False

In [14]:
a.any()

True

# Operaciones lógicas elemento por elemento

In [31]:
a = np.array([True, True, False, True])
b = np.array([False, False, True, True])

In [38]:
print("a & b =", a & b)
print("a | b =", a | b)
print("a ^ b =", a ^ b)
print("~ b =", ~ b)

a & b = [False False False  True]
a | b = [ True  True  True  True]
a ^ b = [ True  True  True False]
~ b = [ True  True False False]


# Constantes

$$ \huge  \pi, e $$

In [21]:
print('pi =', np.pi)
print('e =', np.e)

pi = 3.141592653589793
e = 2.718281828459045


# Funciones en Numpy

## Trigonométricas

Para las funciones trigonométricas el ángulo debe estar dado en radianes

* Tangente: $ \hspace{1 cm} \large \textrm{np.tan()}$

* Seno: $ \hspace{1 cm} \large \textrm{np.sin()}$

* Coseno: $ \hspace{1 cm} \large \textrm{np.cos()}$

* Trigonométricas inversas: $ \hspace{1 cm} \large \textrm{np.arctan(), np.arcsin(), np.arccos()}$

* Hipotenusa: $ \hspace{1 cm} \large \textrm{np.hypot()}$

* Radianes a grados: $ \hspace{1 cm} \large \textrm{np.rad2deg()}$

* Grados a radianes: $ \hspace{1 cm} \large \textrm{np.deg2rad()}$

## Hiperbólicas

* Tangente: $ \hspace{1 cm} \large \textrm{np.tanh()}$

* Seno: $ \hspace{1 cm} \large \textrm{np.sinh()}$

* Coseno: $ \hspace{1 cm} \large \textrm{np.cosh()}$

* Trigonométricas inversas: $ \hspace{1 cm} \large \textrm{np.arctanh(), np.arcsinh(), np.arccosh()}$

## Exponencial y Logarítmica

* Exponencial: $ \hspace{1 cm} \large \textrm{np.exp()}$

* Logarítmica: $ \hspace{1 cm} \large \textrm{np.log()}$

* Logaritmo en base 10: $ \hspace{1 cm} \large \textrm{np.log10()}$

* Logaritmo en base 2: $ \hspace{1 cm} \large \textrm{np.log2()}$

## Otras funciones

* Conjugado: $ \hspace{1 cm} \large \textrm{np.conj()}$

* Raiz cuadrada: $ \hspace{1 cm} \large \textrm{np.sqrt()}$

* Valor absoluto: $ \hspace{1 cm} \large \textrm{np.absolute()}$

* Valores absolutos: $ \hspace{1 cm} \large \textrm{np.fabs()}$

* Función signo: $ \hspace{1 cm} \large \textrm{np.sign()}$

* Máximo / mínimo:  $ \hspace{1 cm} \large \textrm{np.maximum() / \textrm{np.minimum()}$


In [ ]:
a = [-1, -2, 3, -5]

In [22]:
np.absolute(a)

array([ True,  True, False,  True])

In [26]:
a = [-1, -2, 3, -5]

In [27]:
np.fabs(a)

array([1., 2., 3., 5.])

In [28]:
a

[-1, -2, 3, -5]

## Funciones de estadística básica

* Media aritmética: $ \hspace{1 cm} \large \textrm{np.mean()}$

* Desviación estándar: $ \hspace{1 cm} \large \textrm{np.std()}$

* Varianza: $ \hspace{1 cm} \large \textrm{np.var()}$

## Funciones de álgebra lineal

* Producto interno: $ \hspace{1 cm} \large \textrm{np.dot()}$

* Prodicto cruz: $ \hspace{1 cm} \large \textrm{np.cross()}$


# Otras utilidades de Numpy

## Crear un intervalo de numeros reales igualmente espaciados

In [42]:
np.linspace(-5, 5, 20)

array([-5.        , -4.47368421, -3.94736842, -3.42105263, -2.89473684,
       -2.36842105, -1.84210526, -1.31578947, -0.78947368, -0.26315789,
        0.26315789,  0.78947368,  1.31578947,  1.84210526,  2.36842105,
        2.89473684,  3.42105263,  3.94736842,  4.47368421,  5.        ])

## Crear un arreglo de numeros enteros igualmente espaciados

In [44]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [43]:
np.arange(3, 7, 2)

array([3, 5])

In [69]:
help(np.where)

Help on built-in function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called whe

In [39]:
help(np.zeros)


Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [ ]:
help(np.ones)

In [49]:
c = np.full((2,2), 7)  # Create a constant array
print(c)  

[[7 7]
 [7 7]]


In [118]:
help(np.eye)


Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

In [ ]:
help(np.random.random)

In [40]:
np.sum([1, 2, 3, 4, 5, 6, 7])

28